/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export function Planet(props) {
  const shapeContainer = useRef(null);
  const spheresContainer = useRef(null);
  const ringContainer = useRef(null);
  const entranceProgress = useRef(0);
  const { nodes, materials } = useGLTF("/models/Planet.glb");

  useFrame(({ clock }, delta) => {
    const shape = shapeContainer.current;
    const spheres = spheresContainer.current;
    const ring = ringContainer.current;

    if (!shape || !spheres || !ring) return;

    const elapsed = clock.getElapsedTime();
    entranceProgress.current = Math.min(1, entranceProgress.current + delta / 2.8);
    const easedEntrance = 1 - Math.pow(1 - entranceProgress.current, 3);

    shape.position.y = 5 * (1 - easedEntrance) + Math.sin(elapsed * 0.7) * 0.08;
    shape.rotation.x = Math.sin(elapsed * 0.28) * 0.03;
    shape.rotation.z = Math.sin(elapsed * 0.22) * 0.03;

    spheres.rotation.y += delta * 0.32;
    ring.rotation.z += delta * 0.24;
    ring.rotation.x = -0.124 + Math.sin(elapsed * 0.34) * 0.025;
    ring.rotation.y = 0.123 + Math.cos(elapsed * 0.3) * 0.025;
  });

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group ref={spheresContainer}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["Material.002"]}
          rotation={[0, 0, 0.741]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere2.geometry}
          material={materials["Material.001"]}
          position={[0.647, 1.03, -0.724]}
          rotation={[0, 0, 0.741]}
          scale={0.223}
        />
      </group>
      <mesh
        ref={ringContainer}
        castShadow
        receiveShadow
        geometry={nodes.Ring.geometry}
        material={materials["Material.001"]}
        rotation={[-0.124, 0.123, -0.778]}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload("/models/Planet.glb");
